import { Box, Button, Heading } from '@chakra-ui/react'
import { useEffect, useState } from 'react'

export const Popup = () => {
  const [count, setCount] = useState(0)
  const link = 'https://github.com/guocaoyi/create-chrome-ext'

  const minus = () => {
    if (count > 0) setCount(count - 1)
  }

  const add = () => setCount(count + 1)

  // useEffect(() => {
  //   chrome.storage.sync.get(['count'], (result) => {
  //     setCount(result.count || 0)
  //   })
  // }, [])

  // useEffect(() => {
  //   chrome.storage.sync.set({ count })
  //   chrome.runtime.sendMessage({ type: 'COUNT', count })
  // }, [count])

  return (
    <main className="flex flex-col gap-4 p-2 w-[300px]">
      <Heading size="lg">Popup Page</Heading>
      <div className="flex gap-2 items-center">
        <Button onClick={minus} disabled={count <= 0}>
          -
        </Button>
        <Box fontSize="lg">{count}</Box>
        <Button onClick={add}>+</Button>
      </div>
      <a href={link} target="_blank">
        generated by create-chrome-ext
      </a>
    </main>
  )
}

export default Popup
