import { useState, useEffect } from 'react'

export const Options = () => {
  const [countSync, setCountSync] = useState(0)
  const link = 'https://github.com/guocaoyi/create-chrome-ext'

  useEffect(() => {
    try {
      chrome.storage.sync.get(['count'], (result) => {
        setCountSync(result.count || 0)
      })

      chrome.runtime.onMessage.addListener((request) => {
        if (request.type === 'COUNT') {
          setCountSync(request.count || 0)
        }
      })
    } catch (e) {
      console.error(e)
    }
  }, [])

  return (
    <main>
      <h3>Options Page</h3>
      <h4>Count from Popup: {countSync}</h4>
      <form>
        <div className="form-control">
          <label>OpenAI API Key:</label>
          <input type="text" />
        </div>
        <div className="form-control">
          <label>API Key:</label>
          <input type="text" />
        </div>
      </form>
      <a href={link} target="_blank">
        generated by create-chrome-ext
      </a>
    </main>
  )
}

export default Options
